### PR TITLE
make project runnable

### PR DESCRIPTION
**Pull request by efiop**
Currently there is no remote, so users have to manually download the file. With this PR it is handled by dvc.

### CODE REVIEW

**Comment by efiop** [comment]
@dberenbaum You might need to approve the first run for github actions here (should be a button above).

**Comment by efiop** [comment]
For the record: clarified that this was meant for `exp init`, so the data was expected to just be there. Closing.

**Comment by dberenbaum** [comment]
How were you planning to use the repo? Happy to merge it either into `dvc` or a separate branch, or fork it. There aren't any dependencies on it, it's just a repo I mainly use now for examples.

**Comment by efiop** [comment]
@dberenbaum We already use it successfully in `exp show` test. Wanted to use it for `exp run` too, but there are bigger problems that are unrelated to this, so decided to wait for now. No need to merge this.

**Pull request closed without merging**
